### ISSUE TITLE
Search keyword error

### ISSUE THREAD

**Issue by bewuluck0912** [kotvertolet/youtube-audio-player#1]
![error2](https://user-images.githubusercontent.com/11924427/63827415-fa6ce600-c99d-11e9-9b67-59da79eac4cc.gif)

Logcat :  io.reactivex.exceptions.CompositeException: 2 exceptions occurred.

**Comment by antonyhaman** [comment]
@bawulee0912 could you please provide more detailed report about this issue?

**Comment by bawulee0912** [comment]
> @bawulee0912 could you please provide more detailed report about this issue?

First, take a look at the image
