### ISSUE TITLE
Move to Fastlane file structure

### ISSUE THREAD

**Issue by antonyhaman** [kotvertolet/youtube-audio-player#11]
https://github.com/kotvertolet/youtube-audio-player/issues/7#issuecomment-612659121

**Comment by IzzySoft** [comment]
Ugh… I should read first… Just created a duplicate in #12 :scream: Fixing that, moving the contents over here:

Great you consider Fastlane! Again, please let me know when it's there (I might also have "improvement suggestions" then), so I include it here as well (for now, the changelogs automatically and screenshots manually – in the future, maybe more). For the screenshots: I recommend ***not*** framing them (wastes the already minimal screen-estate on phones). I usually shrink them to a width of 350px; if you want to have a higher res, no issue as I srhink them myself anyway – but I'd not make them too big.

Attached you can find a "starter package" you'd just need to unzip into the root directory of your project: [com.github.kotvertolet.youtubeaudioplayer_fastlane.zip](https://github.com/kotvertolet/youtube-audio-player/files/4467220/com.github.kotvertolet.youtubeaudioplayer_fastlane.zip)

To fill the gaps, find a quick overview here: [Fastlane file structure](https://gitlab.com/snippets/1895688)

**Comment by antonyhaman** [comment]
@IzzySoft Done, check if everything is correct plase. Btw, I've updated readme too.

**Comment by IzzySoft** [comment]
I'd avoid `<h1|2>` headers in `full_decription.txt` – that will look ugly in the F-Droid app and on the website. Also, no need to put the app name in a big header on top – I'm not aware of any place where the description is used without mentioning the app name along already, so that is redundant.

Apart from that, it looks fine :smiley:

**Comment by antonyhaman** [comment]
@IzzySoft Thanks, fixed.

**Comment by IzzySoft** [comment]
Yes, much better! If you wish you can also put the `<b>Features</b>` between `<p></p>` – and later add a `changelogs/<versionCode>.txt` right before tagging a new release.

Thanks a lot!

**Comment by antonyhaman** [comment]
Please, check the latest commit if everything is right this time )

**Comment by IzzySoft** [comment]
Perfect! :tada: :+1: Provided your versionCodes are 110 and 111 that is. `build.gradle` says 1 and 2 – so the files should be `1.txt` resp. `2.txt` (`versionCode`, not `versionName-without-dots` :wink:)

**Comment by IzzySoft** [comment]
PS: Please do NOT delete old releases, just keep them and add new ones. Tags are not consuming any space. And remember not to repeat `versionCode`s – always increase them before creating the APK and tagging the release. You already had 2 versions, so VC should be > 2 with the next one.

**Comment by antonyhaman** [comment]
@IzzySoft Okey, I fixed that.
>PS: Please do NOT delete old releases, just keep them and add new ones. Tags are not consuming any space. And remember not to repeat versionCodes – always increase them before creating the APK and tagging the release. You already had 2 versions, so VC should be > 2 with the next one.

Okay, I'll remeber that :) I'm closing this issue for now if you yave any other suggestions or recommendations feel free to create a new issue

**Comment by IzzySoft** [comment]
Will do! Thanks for your great work, was fun working with you on this! Keep it up :smile:

PS: Looking forward to your next release. Just switched the config to fetch from releases now, including Fastlane per-release changelogs. Next update run in about 21h :wink:
