### ISSUE TITLE
Please sign your APK

### ISSUE THREAD

**Issue by IzzySoft** [kotvertolet/youtube-audio-player#7]
Your latest APK is lacking a valid signature:

```
DOES NOT VERIFY
ERROR: No JAR signatures
ERROR: com.github.kotvertolet.youtubeaudioplayer_2020-04-02.apk: 
ERROR: Old APK signature failed to verify: com.github.kotvertolet.youtubeaudioplayer_2020-04-02.apk

jar is unsigned.
```

Could you please replace it with a signed (v1+v2) APK? Thanks!

**Comment by antonyhaman** [comment]
@IzzySoft Check now, should be fixed in the latest release. Btw it's also announced some new improvements to the app.

**Comment by IzzySoft** [comment]
Thanks! Yes, this worked out fine. Just `versionName` is a bit strange, considering you started with v1.0 about a year ago, which was followed by v1.1 :rofl: Shouldn't the last release be v1.1.1, v1.2 or something like that, instead of v0.1.1?

Great also to see the size went down from ~30M to ~5M per APK, yay! And you finally increased `versionCode` :+1: So I've adjusted the settings for your app to allow for 3 versions, which now easily fit inside the 30M limit (ugh, ahem, referring [to this](https://apt.izzysoft.de/fdroid/index/apk/com.github.kotvertolet.youtubeaudioplayer) – apologies for the late disclosure).

> also announced some new improvements to the app

I don't know where to see that announcement (outside of the app itself). Maybe you should consider using [releases](https://github.com/kotvertolet/youtube-audio-player/releases)? There you could add release notes. And it would keep your repo more compact if the APKs where attached to `releases/` instead of living inside the repo.

While on it: what do you think about [Fastlane file structure](https://gitlab.com/snippets/1895688)? Not that it much matters to you as you cannot publish to Google Play anyway – but my updater would pick the per-release changelogs from there, and should you get your app listed in F-Droid's main repo they'd also pick summary, description and screenshots.

**Comment by antonyhaman** [comment]
>  Just versionName is a bit strange, considering you started with v1.0 about a year ago, which was followed by v1.1 🤣 Shouldn't the last release be v1.1.1, v1.2 or something like that, instead of v0.1.1?

Ahah, you're right, it's strange ) In fact I'm not an android developer really and I'm not used to Gradle (I'm dedicated Maven user), I've found out about versionName  and versionCode couple hours ago, when I started to google why my app can't be updated with new apk. So you suggest to start versioning from v1.1.1? Or start it all over from 1.0.0?

>Great also to see the size went down from ~30M to ~5M per APK, yay!

Currently I'm trying to get proguard work again, apk size will shrink even more.

>ugh, ahem, referring to this – apologies for the late disclosure

Wow, thanks for publishing this!

> Maybe you should consider using releases? There you could add release notes. And it would keep your repo more compact if the APKs where attached to releases/ instead of living inside the repo.

Yeah, It would be nice tough. I will do it that way next time.

>While on it: what do you think about Fastlane file structure? Not that it much matters to you as you cannot publish to Google Play anyway – but my updater would pick the per-release changelogs from there, and should you get your app listed in F-Droid's main repo they'd also pick summary, description and screenshots.

Okay, sounds reasonable, I'll do that. 

Thanks for your suggestions a lot! Please let me know if you have any left )

**Comment by IzzySoft** [comment]
> So you suggest to start versioning from v1.1.1?

I'd just suggest keeping it straight with future releases. If you wish to "cleanup" now, just rebuild the APK with v1.1.1 as versionName (keep the versionCode *this time* as not too many people will already have loaded it) – but when doing so please drop me a note once the file has been replaced, as I'd need to pull that one manually.

> Currently I'm trying to get proguard work again, apk size will shrink even more.

Yay, it gets even cooler :tada:

> Wow, thanks for publishing this!

Gladly! And please let me know when you switched to `releases/` as I need to adjust this here then as well for new APKs to be picked up. Besides, if you wish to point out in the Readme that your app is available with my repo (and thus can be installed/updated using the F-Droid client), you're [welcome to use my badge](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for that:

<img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png" width="220">

Great you consider Fastlane! To help keeping things organized, I've ~~split this off to #12~~ added the details to #11.

As for "recommendations left": Sure, as soon as they come to mind :smile:

Thanks a lot – it's fun to "brain storm" if ideas fall on such fertile ground :smiley:
